# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Jinzhao's Learning Notes
author: Jinzhao Yu
logo: images/ai-vs-ml-1200.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off' # 所有的notebook都会直接把跑好的输出generate出来而不会重新运行ipynb！
  allow_errors: true

# Define the name of the latex output file for PDF builds
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Jinzhao-Yu/Learning-Notes  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  comments:
    hypothesis: true

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    language: en # Change language to English. 没有这一行会是强行翻译的中文
